### ISSUE TITLE
Django Support

### ISSUE THREAD

**Issue by AceFire6** [PeRDy/apistar-crud#2]
Hi, @PeRDy . 

Thank you for writing this package. It looks really useful 👍 

I'm actually wanting to use it in one of my projects, however, we use Django there.

I would like to contribute by adding or helping to add Django support. Unfortunately, I am not sure where to start. I've never really used the Django ORM outside of a pure Django project.

Where would a good place to start be?

Thank you 😄

**Comment by perdy** [comment]
I'd be glad to have Django support in this project but mainly because of the changes on API Star v0.4.0, I'm in the same position as you.

My suggestion is to ask in [API Star forum](https://discuss.apistar.org/) or create an issue directly in API Star project to see how people is working with Django ORM on versions above 0.4.0 and we can draft something.
